### ISSUE TITLE
CI checklist

### ISSUE THREAD

**Issue by luser** [luser/sccache2#5]
- [x] Travis-CI builds+tests for Linux
- [x] Travis-CI builds+tests for OS X
- [x] Appveyor builds+tests for Windows
